### ISSUE TITLE
 how do I save to 1 folder?

### ISSUE THREAD

**Issue by sasholy** [Karthik-HR0/refx#1]
Hi, how do I save to 1 folder?

What's this file for, how do I see it? - https://github.com/Karthik-HR0/refx/blob/main/V1.0/refx

thx.

**Comment by Karthik-HR0** [comment]
> Hi, how do I save to 1 folder?
> 
> What's this file for, how do I see it? - https://github.com/Karthik-HR0/refx/blob/main/V1.0/refx
> 
> thx. .

**Comment by Karthik-HR0** [comment]
> Hi, how do I save to 1 folder?
> 
> What's this file for, how do I see it? - https://github.com/Karthik-HR0/refx/blob/main/V1.0/refx
> 
> thx.

In V1.0 the tool is already built by same source code. You can just use it by cloning the repo then run or  install manually run. I uploaded the source code in V1.0
